import { Age, Prisma, PrismaClient } from '@prisma/client'
import { normalizeCityName } from 'src/utils/normalizeCityName'
import { randomUUID, UUID } from 'crypto'

const prisma = new PrismaClient()

async function main() {
  console.log('🌱 Starting seed...')

  const orgs = [
    {
      id: randomUUID(),
      name: 'Amigos dos Animais',
      description: 'ONG dedicada ao resgate e adoção de animais.',
      email: 'contato@amigos.org',
      password_hash: 'senha123',
      whatsapp: '11999999999',
      address: 'Rua das Flores, 123',
      city: normalizeCityName('São Paulo'),
      state: 'SP',
      cep: '01001000',
    },
    {
      id: randomUUID(),
      name: 'Patas Felizes',
      description: 'Acolhimento e adoção de cães e gatos.',
      email: 'contato@patasfelizes.org',
      password_hash: 'senha123',
      whatsapp: '23999999999',
      address: 'Avenida Central, 456',
      city: normalizeCityName('Rio de Janeiro'),
      state: 'RJ',
      cep: '20040002',
    },
    {
      id: randomUUID(),
      name: 'Mundo Animal',
      description: 'Cuidando dos animais que precisam de um lar.',
      email: 'contato@mundoanimal.org',
      password_hash: 'senha123',
      whatsapp: '41999999999',
      address: 'Rua dos Bichos, 789',
      city: normalizeCityName('Curitiba'),
      state: 'PR',
      cep: '80010030',
    },
    {
      id: randomUUID(),
      name: 'SOS Pet',
      description: 'Resgate de animais em situação de risco.',
      email: 'contato@sospet.org',
      password_hash: 'senha123',
      whatsapp: '31999990004',
      address: 'Rua Solidária, 321',
      city: normalizeCityName('Belo Horizonte'),
      state: 'MG',
      cep: '30120010',
    },
    {
      id: randomUUID(),
      name: 'Anjos de Patas',
      description: 'ONG dedicada ao bem-estar dos animais.',
      email: 'contato@anjosdepatas.org',
      password_hash: 'senha123',
      whatsapp: '51999990005',
      address: 'Avenida Amor Animal, 654',
      city: normalizeCityName('Porto Alegre'),
      state: 'RS',
      cep: '90040020',
    },
  ]

  for (const org of orgs) {
    const existingOrg = await prisma.org.findUnique({
      where: { email: org.email },
    })

    if (!existingOrg) {
      await prisma.org.create({ data: { ...org, id: randomUUID() } })
    } else {
      console.log(`⚠️ Org already exists: ${org.email}`)
    }
  }
  console.log('✅ Orgs created')

  type PetType = Prisma.PetUncheckedCreateInput & { photos: string[] }
  const pets: PetType[] = [
    {
      id: randomUUID(),
      org_id: orgs[0].id,
      name: 'Apollo',
      description: 'Cão dócil e adora crianças.',
      age: Age.adult,
      size: 'medium',
      energy_level: 'high',
      independence_level: 'medium',
      environment: 'medium',
      breed: 'Bernedoodle',
      sex: 'male',
      type: 'dog',
      city: normalizeCityName('São Paulo'),
      state: 'SP',
      photos: ['/dogs/bernedoodle.jpg'],
    },
    {
      id: randomUUID(),
      org_id: orgs[0].id,
      name: 'Maya',
      description: 'Cão inteligente e ágil, ótimo para famílias.',
      age: Age.puppy,
      size: 'medium',
      energy_level: 'high',
      independence_level: 'medium',
      environment: 'medium',
      breed: 'Border Collie',
      sex: 'female',
      type: 'dog',
      city: normalizeCityName('São Paulo'),
      state: 'SP',
      photos: ['/dogs/border-collie.png'],
    },
    {
      id: randomUUID(),
      org_id: orgs[1].id,
      name: 'Zeca',
      description: 'Muito carinhoso e companheiro.',
      age: Age.adult,
      size: 'large',
      energy_level: 'high',
      independence_level: 'medium',
      environment: 'large',
      breed: 'Vira-lata caramelo',
      sex: 'male',
      type: 'dog',
      city: normalizeCityName('Rio de Janeiro'),
      state: 'RJ',
      photos: ['/dogs/caramelo.png'],
    },
    {
      id: randomUUID(),
      org_id: orgs[1].id,
      name: 'Lili',
      description: 'Pequena, carinhosa e adora brincar.',
      age: Age.adult,
      size: 'small',
      energy_level: 'high',
      independence_level: 'low',
      environment: 'small',
      breed: 'Chihuahua',
      sex: 'female',
      type: 'dog',
      city: normalizeCityName('Rio de Janeiro'),
      state: 'RJ',
      photos: ['/dogs/chihuahua.jpg'],
    },
    {
      id: randomUUID(),
      org_id: orgs[2].id,
      name: 'Ragnar',
      description: 'Muito atento, excelente cão de guarda.',
      age: Age.senior,
      size: 'large',
      energy_level: 'medium',
      independence_level: 'high',
      environment: 'large',
      breed: 'Doberman',
      sex: 'male',
      type: 'dog',
      city: normalizeCityName('Curitiba'),
      state: 'PR',
      photos: ['/dogs/doberman.jpg'],
    },
    {
      id: randomUUID(),
      org_id: orgs[2].id,
      name: 'Lola',
      description: 'Muito doce, brincalhona e sociável.',
      age: Age.puppy,
      size: 'large',
      energy_level: 'high',
      independence_level: 'medium',
      environment: 'large',
      breed: 'Golden Retriever',
      sex: 'female',
      type: 'dog',
      city: normalizeCityName('Curitiba'),
      state: 'PR',
      photos: ['/dogs/golden-retriever.jpg'],
    },
    {
      id: randomUUID(),
      org_id: orgs[3].id,
      name: 'Amora',
      description: 'Calma, dócil e muito companheira.',
      age: Age.senior,
      size: 'small',
      energy_level: 'low',
      independence_level: 'medium',
      environment: 'small',
      breed: 'Kokoni',
      sex: 'female',
      type: 'dog',
      city: normalizeCityName('Belo Horizonte'),
      state: 'MG',
      photos: ['/dogs/kokoni.jpg'],
    },
    {
      id: randomUUID(),
      org_id: orgs[3].id,
      name: 'Zeus',
      description: 'Grande, protetor e extremamente leal.',
      age: Age.adult,
      size: 'large',
      energy_level: 'high',
      independence_level: 'high',
      environment: 'large',
      breed: 'Kuvasz',
      sex: 'male',
      type: 'dog',
      city: normalizeCityName('Belo Horizonte'),
      state: 'MG',
      photos: ['/dogs/kuvaszs.jpg'],
    },
    {
      id: randomUUID(),
      org_id: orgs[4].id,
      name: 'Bruno',
      description: 'Extremamente carinhoso e brincalhão.',
      age: Age.puppy,
      size: 'large',
      energy_level: 'high',
      independence_level: 'medium',
      environment: 'large',
      breed: 'Labrador Retriever',
      sex: 'male',
      type: 'dog',
      city: normalizeCityName('Porto Alegre'),
      state: 'RS',
      photos: ['/dogs/labrador-retriever.jpg'],
    },
    {
      id: randomUUID(),
      org_id: orgs[4].id,
      name: 'Stella',
      description: 'Meiga, sociável e se dá bem com crianças.',
      age: Age.adult,
      size: 'medium',
      energy_level: 'medium',
      independence_level: 'low',
      environment: 'medium',
      breed: 'Lapphund Finlandês',
      sex: 'female',
      type: 'dog',
      city: normalizeCityName('Porto Alegre'),
      state: 'RS',
      photos: ['/dogs/lapphund-finlandes.jpg'],
    },
    {
      id: randomUUID(),
      org_id: orgs[4].id,
      name: 'Mia',
      description: 'Gata carinhosa, ama colo e é muito sociável.',
      age: Age.adult,
      size: 'medium',
      energy_level: 'medium',
      independence_level: 'low',
      environment: 'medium',
      breed: 'Maine Coon',
      sex: 'female',
      type: 'cat',
      city: normalizeCityName('Porto Alegre'),
      state: 'RS',
      photos: ['/cats/maine-coon.jpg'],
    },
    {
      id: randomUUID(),
      org_id: orgs[4].id,
      name: 'Luna',
      description: 'Gata curiosa, inteligente e muito brincalhona.',
      age: Age.adult,
      size: 'small',
      energy_level: 'high',
      independence_level: 'medium',
      environment: 'small',
      breed: 'Tabby',
      sex: 'female',
      type: 'cat',
      city: normalizeCityName('Porto Alegre'),
      state: 'RS',
      photos: ['/cats/tabby.jpg'],
    },
    {
      id: randomUUID(),
      org_id: orgs[4].id,
      name: 'Simba',
      description: 'Gato dócil e companheiro, adora brincar com bolinhas.',
      age: Age.adult,
      size: 'small',
      energy_level: 'medium',
      independence_level: 'medium',
      environment: 'small',
      breed: 'Tabby',
      sex: 'male',
      type: 'cat',
      city: normalizeCityName('Porto Alegre'),
      state: 'RS',
      photos: ['/cats/tabby2.jpg'],
    },
    {
      id: randomUUID(),
      org_id: orgs[4].id,
      name: 'Nina',
      description: 'Gata tranquila, carinhosa e se adapta bem a apartamentos.',
      age: Age.adult,
      size: 'small',
      energy_level: 'low',
      independence_level: 'medium',
      environment: 'small',
      breed: 'Van Turco',
      sex: 'female',
      type: 'cat',
      city: normalizeCityName('Porto Alegre'),
      state: 'RS',
      photos: ['/cats/van-turco.jpg'],
    },
    {
      id: randomUUID(),
      org_id: orgs[0].id,
      name: 'Luna',
      description: 'Gata carinhosa, ideal para famílias com crianças.',
      age: Age.adult,
      size: 'small',
      energy_level: 'medium',
      independence_level: 'high',
      environment: 'medium',
      breed: 'Pelo Curto Brasileiro',
      sex: 'female',
      type: 'cat',
      city: normalizeCityName('São Paulo'),
      state: 'SP',
      photos: ['/cats/pelo-curto-brasileiro.png'],
    },
    {
      id: randomUUID(),
      org_id: orgs[1].id,
      name: 'Milo',
      description: 'Gato curioso, adora explorar e brincar.',
      age: Age.senior,
      size: 'medium',
      energy_level: 'high',
      independence_level: 'medium',
      environment: 'large',
      breed: 'Pelo Curto Inglês',
      sex: 'male',
      type: 'cat',
      city: normalizeCityName('Rio de Janeiro'),
      state: 'RJ',
      photos: ['/cats/pelo-curto-ingles.jpg'],
    },
    {
      id: randomUUID(),
      org_id: orgs[2].id,
      name: 'Bella',
      description: 'Gata majestosa, gosta de atenção e conforto.',
      age: Age.adult,
      size: 'large',
      energy_level: 'low',
      independence_level: 'low',
      environment: 'medium',
      breed: 'Maine Coon',
      sex: 'female',
      type: 'cat',
      city: normalizeCityName('Curitiba'),
      state: 'PR',
      photos: ['/cats/maine-coon-3.jpg'],
    },
    {
      id: randomUUID(),
      org_id: orgs[3].id,
      name: 'Simba',
      description: 'Gato elegante, vocal e muito afetuoso.',
      age: Age.senior,
      size: 'medium',
      energy_level: 'medium',
      independence_level: 'high',
      environment: 'small',
      breed: 'Siamês',
      sex: 'male',
      type: 'cat',
      city: normalizeCityName('Belo Horizonte'),
      state: 'MG',
      photos: ['/cats/siames.jpg'],
    },
    {
      id: randomUUID(),
      org_id: orgs[4].id,
      name: 'Thor',
      description: 'Cão leal, ótimo para companhia e passeios.',
      age: Age.adult,
      size: 'medium',
      energy_level: 'high',
      independence_level: 'medium',
      environment: 'large',
      breed: 'Cocker Spaniel Inglês',
      sex: 'male',
      type: 'dog',
      city: normalizeCityName('Porto Alegre'),
      state: 'RS',
      photos: ['/dogs/cocker-spaniel-ingles.jpg'],
    },
    {
      id: randomUUID(),
      org_id: orgs[4].id,
      name: 'Coco',
      description: 'Cãozinho alegre, perfeito para apartamentos.',
      age: Age.puppy,
      size: 'small',
      energy_level: 'medium',
      independence_level: 'low',
      environment: 'small',
      breed: 'Corgi',
      sex: 'female',
      type: 'dog',
      city: normalizeCityName('Florianópolis'),
      state: 'SC',
      photos: ['/dogs/corgi.jpg'],
    },
    {
      id: randomUUID(),
      org_id: orgs[4].id,
      name: 'Zara',
      description: 'Cão elegante, gosta de correr e explorar.',
      age: Age.puppy,
      size: 'large',
      energy_level: 'high',
      independence_level: 'high',
      environment: 'large',
      breed: 'Galgo Afegão',
      sex: 'female',
      type: 'dog',
      city: normalizeCityName('Recife'),
      state: 'PE',
      photos: ['/dogs/galgo-afegao.jpg'],
    },
    {
      id: randomUUID(),
      org_id: orgs[3].id,
      name: 'Buddy',
      description: 'Cão amigável, adora interagir com pessoas.',
      age: Age.adult,
      size: 'large',
      energy_level: 'medium',
      independence_level: 'low',
      environment: 'medium',
      breed: 'Golden Retriever',
      sex: 'male',
      type: 'dog',
      city: normalizeCityName('Brasília'),
      state: 'DF',
      photos: ['/dogs/golden-retriever2.jpg'],
    },
    {
      id: randomUUID(),
      org_id: orgs[0].id,
      name: 'Lola',
      description: 'Cãozinho carinhoso, ótimo para lares pequenos.',
      age: Age.senior,
      size: 'small',
      energy_level: 'low',
      independence_level: 'medium',
      environment: 'small',
      breed: 'Salsicha',
      sex: 'female',
      type: 'dog',
      city: normalizeCityName('Fortaleza'),
      state: 'CE',
      photos: ['/dogs/salsicha2.jpg'],
    },
    {
      id: randomUUID(),
      org_id: orgs[0].id,
      name: 'Apollo',
      description:
        'Gato majestoso de pelagem exuberante, muito carinhoso e sociável.',
      age: Age.adult,
      size: 'large',
      energy_level: 'medium',
      independence_level: 'medium',
      environment: 'medium',
      breed: 'Maine Coon',
      sex: 'male',
      type: 'cat',
      city: normalizeCityName('São Paulo'),
      state: 'SP',
      photos: ['/cats/maine-coon-3.jpg'],
    },
    {
      id: randomUUID(),
      org_id: orgs[0].id,
      name: 'Maya',
      description: 'Gata exótica de origem árabe, elegante e independente.',
      age: Age.adult,
      size: 'medium',
      energy_level: 'medium',
      independence_level: 'high',
      environment: 'medium',
      breed: 'Mau Árabe',
      sex: 'female',
      type: 'cat',
      city: normalizeCityName('São Paulo'),
      state: 'SP',
      photos: ['/cats/mau-arabe.jpg'],
    },
    {
      id: randomUUID(),
      org_id: orgs[1].id,
      name: 'Zeca',
      description:
        'Gato laranja carinhoso, típico brasileiro, muito brincalhão.',
      age: Age.adult,
      size: 'medium',
      energy_level: 'high',
      independence_level: 'medium',
      environment: 'medium',
      breed: 'Tabby Laranja',
      sex: 'male',
      type: 'cat',
      city: normalizeCityName('Rio de Janeiro'),
      state: 'RJ',
      photos: ['/cats/tabby-laranja.jpg'],
    },
    {
      id: randomUUID(),
      org_id: orgs[1].id,
      name: 'Lila',
      description: 'Gata tigrada pequena e ágil, muito curiosa e afetuosa.',
      age: Age.puppy,
      size: 'small',
      energy_level: 'high',
      independence_level: 'medium',
      environment: 'small',
      breed: 'Tabby',
      sex: 'female',
      type: 'cat',
      city: normalizeCityName('Campo Grande'),
      state: 'MS',
      photos: ['/cats/tabby3.png'],
    },
    {
      id: randomUUID(),
      org_id: orgs[2].id,
      name: 'Ragnar',
      description:
        'Gato tigrado robusto, territorialista mas carinhoso com a família.',
      age: Age.adult,
      size: 'medium',
      energy_level: 'medium',
      independence_level: 'high',
      environment: 'medium',
      breed: 'Tabby',
      sex: 'male',
      type: 'cat',
      city: normalizeCityName('Curitiba'),
      state: 'PR',
      photos: ['/cats/tabby4.png'],
    },
    {
      id: randomUUID(),
      org_id: orgs[2].id,
      name: 'Lola',
      description:
        'Cão dourado muito dócil, perfeito para famílias com crianças.',
      age: Age.puppy,
      size: 'large',
      energy_level: 'high',
      independence_level: 'low',
      environment: 'large',
      breed: 'Golden Retriever',
      sex: 'female',
      type: 'dog',
      city: normalizeCityName('Curitiba'),
      state: 'PR',
      photos: ['/dogs/golden-retriever.jpg'],
    },
    {
      id: randomUUID(),
      org_id: orgs[3].id,
      name: 'Coco',
      description: 'Cão pequeno e elegante, calmo e companheiro ideal.',
      age: Age.adult,
      size: 'small',
      energy_level: 'low',
      independence_level: 'medium',
      environment: 'small',
      breed: 'Cocker Spaniel Inglês',
      sex: 'female',
      type: 'dog',
      city: normalizeCityName('Belo Horizonte'),
      state: 'MG',
      photos: ['/dogs/cokcer-spaniel-ingles2.jpg'],
    },
    {
      id: randomUUID(),
      org_id: orgs[3].id,
      name: 'Zeus',
      description: 'Kuvasz majestoso, cão guardião leal e protetor da família.',
      age: Age.adult,
      size: 'large',
      energy_level: 'medium',
      independence_level: 'high',
      environment: 'large',
      breed: 'Kuvasz',
      sex: 'male',
      type: 'dog',
      city: normalizeCityName('Belo Horizonte'),
      state: 'MG',
      photos: ['/dogs/kuvaszs.jpg'],
    },
    {
      id: randomUUID(),
      org_id: orgs[4].id,
      name: 'Bruno',
      description:
        'Labrador jovem e brincalhão, extremamente sociável e carinhoso.',
      age: Age.puppy,
      size: 'large',
      energy_level: 'high',
      independence_level: 'low',
      environment: 'large',
      breed: 'Labrador Retriever',
      sex: 'male',
      type: 'dog',
      city: normalizeCityName('Porto Alegre'),
      state: 'RS',
      photos: ['/dogs/labrador-retriever2.png'],
    },
    {
      id: randomUUID(),
      org_id: orgs[1].id,
      name: 'Lili',
      description:
        'Lapphund Finlandês peludo e resistente, ótimo para clima frio.',
      age: Age.adult,
      size: 'medium',
      energy_level: 'high',
      independence_level: 'medium',
      environment: 'medium',
      breed: 'Lapphund Finlandês',
      sex: 'female',
      type: 'dog',
      city: normalizeCityName('Florianópolis'),
      state: 'SC',
      photos: ['/dogs/lapphund-finlandes.jpg'],
    },
    {
      id: randomUUID(),
      org_id: orgs[4].id,
      name: 'Mia',
      description:
        'Cão de raça mista, carinhoso e adaptável a qualquer ambiente.',
      age: Age.adult,
      size: 'medium',
      energy_level: 'medium',
      independence_level: 'medium',
      environment: 'medium',
      breed: 'SRD (Sem Raça Definida)',
      sex: 'female',
      type: 'dog',
      city: normalizeCityName('Porto Alegre'),
      state: 'RS',
      photos: ['/dogs/mixed.jpg'],
    },
    {
      id: randomUUID(),
      org_id: orgs[4].id,
      name: 'Luna',
      description: 'Podengo Português ágil e inteligente, excelente caçador.',
      age: Age.adult,
      size: 'medium',
      energy_level: 'high',
      independence_level: 'high',
      environment: 'medium',
      breed: 'Podengo Português',
      sex: 'female',
      type: 'dog',
      city: normalizeCityName('Porto Alegre'),
      state: 'RS',
      photos: ['/dogs/podengo-portugues.png'],
    },
    {
      id: randomUUID(),
      org_id: orgs[4].id,
      name: 'Simba',
      description:
        'Poochon fofinho, mistura de Poodle com Bichon, muito carinhoso.',
      age: Age.senior,
      size: 'small',
      energy_level: 'medium',
      independence_level: 'low',
      environment: 'small',
      breed: 'Poochon',
      sex: 'male',
      type: 'dog',
      city: normalizeCityName('Porto Alegre'),
      state: 'RS',
      photos: ['/dogs/poochon.jpg'],
    },
    {
      id: randomUUID(),
      org_id: orgs[4].id,
      name: 'Nina',
      description:
        'Pug adorável e brincalhão, perfeito para apartamentos pequenos.',
      age: Age.adult,
      size: 'small',
      energy_level: 'medium',
      independence_level: 'low',
      environment: 'small',
      breed: 'Pug',
      sex: 'female',
      type: 'dog',
      city: normalizeCityName('Porto Alegre'),
      state: 'RS',
      photos: ['/dogs/pug.jpg'],
    },
    {
      id: randomUUID(),
      org_id: orgs[0].id,
      name: 'Luna',
      description:
        'Salsicha carinhosa e corajosa, pequena mas cheia de personalidade.',
      age: Age.adult,
      size: 'small',
      energy_level: 'medium',
      independence_level: 'medium',
      environment: 'small',
      breed: 'Dachshund (Salsicha)',
      sex: 'female',
      type: 'dog',
      city: normalizeCityName('São Paulo'),
      state: 'SP',
      photos: ['/dogs/salsicha.jpg'],
    },
    {
      id: randomUUID(),
      org_id: orgs[1].id,
      name: 'Toby',
      description: 'Samoieda magnífico, peludo e sorridente, muito sociável.',
      age: Age.adult,
      size: 'large',
      energy_level: 'high',
      independence_level: 'medium',
      environment: 'large',
      breed: 'Samoieda',
      sex: 'male',
      type: 'dog',
      city: normalizeCityName('Rio de Janeiro'),
      state: 'RJ',
      photos: ['/dogs/samoieda.jpg'],
    },
    {
      id: randomUUID(),
      org_id: orgs[2].id,
      name: 'Bella',
      description:
        'Samoieda elegante de pelagem branca impecável, muito dócil.',
      age: Age.adult,
      size: 'large',
      energy_level: 'medium',
      independence_level: 'medium',
      environment: 'large',
      breed: 'Samoieda',
      sex: 'female',
      type: 'dog',
      city: normalizeCityName('Curitiba'),
      state: 'PR',
      photos: ['/dogs/samoieda2.jpg'],
    },
    {
      id: randomUUID(),
      org_id: orgs[3].id,
      name: 'Simba',
      description: 'Shiba Inu independente e corajoso, típico cão japonês.',
      age: Age.adult,
      size: 'medium',
      energy_level: 'medium',
      independence_level: 'high',
      environment: 'medium',
      breed: 'Shiba Inu',
      sex: 'male',
      type: 'dog',
      city: normalizeCityName('Belo Horizonte'),
      state: 'MG',
      photos: ['/dogs/shiba-inu.jpg'],
    },
    {
      id: randomUUID(),
      org_id: orgs[4].id,
      name: 'Thor',
      description: 'Shih Tzu carinhoso e peludo, perfeito cão de companhia.',
      age: Age.adult,
      size: 'small',
      energy_level: 'low',
      independence_level: 'low',
      environment: 'small',
      breed: 'Shih Tzu',
      sex: 'male',
      type: 'dog',
      city: normalizeCityName('Porto Alegre'),
      state: 'RS',
      photos: ['/dogs/shih-tzu.jpg'],
    },
    {
      id: randomUUID(),
      org_id: orgs[4].id,
      name: 'Coco',
      description: 'Shih Tzu jovem e brincalhão, ideal para lares acolhedores.',
      age: Age.puppy,
      size: 'small',
      energy_level: 'medium',
      independence_level: 'low',
      environment: 'small',
      breed: 'Shih Tzu',
      sex: 'female',
      type: 'dog',
      city: normalizeCityName('Florianópolis'),
      state: 'SC',
      photos: ['/dogs/shih-tzu2.png'],
    },
    {
      id: randomUUID(),
      org_id: orgs[4].id,
      name: 'Zara',
      description: 'Terrier enérgico e corajoso, pequeno mas cheio de atitude.',
      age: Age.puppy,
      size: 'small',
      energy_level: 'high',
      independence_level: 'high',
      environment: 'small',
      breed: 'Terrier',
      sex: 'female',
      type: 'dog',
      city: normalizeCityName('Recife'),
      state: 'PE',
      photos: ['/dogs/terrier.jpg'],
    },
    {
      id: randomUUID(),
      org_id: orgs[3].id,
      name: 'Buddy',
      description:
        'Nova Scotia Duck Tolling Retriever ativo, ótimo para esportes.',
      age: Age.adult,
      size: 'medium',
      energy_level: 'high',
      independence_level: 'medium',
      environment: 'large',
      breed: 'Nova Scotia Duck Tolling Retriever',
      sex: 'male',
      type: 'dog',
      city: normalizeCityName('Brasília'),
      state: 'DF',
      photos: ['/dogs/toller.jpg'],
    },
    {
      id: randomUUID(),
      org_id: orgs[0].id,
      name: 'Lola',
      description:
        'Toy Poodle pequeno e inteligente, perfeito para apartamentos.',
      age: Age.adult,
      size: 'small',
      energy_level: 'medium',
      independence_level: 'medium',
      environment: 'small',
      breed: 'Toy Poodle',
      sex: 'female',
      type: 'dog',
      city: normalizeCityName('Fortaleza'),
      state: 'CE',
      photos: ['/dogs/toy-poodle.jpg'],
    },
    {
      id: randomUUID(),
      org_id: orgs[0].id,
      name: 'Gata Van Turco',
      description: 'Gata Van Turco exótica, adora água e é muito ativa.',
      age: Age.adult,
      size: 'medium',
      energy_level: 'high',
      independence_level: 'medium',
      environment: 'medium',
      breed: 'Van Turco',
      sex: 'female',
      type: 'cat',
      city: normalizeCityName('Curitiba'),
      state: 'PR',
      photos: ['/cats/van-turca.jpg'],
    },
  ]

  for (const pet of pets) {
    const existingPet = await prisma.pet.findUnique({
      where: { id: pet.id },
    })

    if (!existingPet) {
      await prisma.pet.create({
        data: {
          ...pet,
          photos: {
            create: pet.photos.map((url) => ({
              id: randomUUID(),
              url,
            })),
          },
        },
      })
    } else {
      console.log(`⚠️ Pet already exists: ${pet.name} - (${pet.id})`)
    }
  }

  console.log('✅ Pets created')

  console.log('🌱 Seed finished successfully!')
}

main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })
