import { Age, Prisma, PrismaClient } from '@prisma/client'
import { normalizeCityName } from 'src/utils/normalizeCityName'
import { randomUUID, UUID } from 'crypto'

const prisma = new PrismaClient()

async function main() {
  console.log('🌱 Starting seed...')

  const orgs = [
    {
      id: randomUUID(),
      name: 'Amigos dos Animais',
      description: 'ONG dedicada ao resgate e adoção de animais.',
      email: 'contato@amigos.org',
      password_hash: 'senha123',
      whatsapp: '11999990001',
      address: 'Rua das Flores, 123',
      city: normalizeCityName('São Paulo'),
      state: 'SP',
      cep: '01001000',
    },
    {
      id: randomUUID(),
      name: 'Patas Felizes',
      description: 'Acolhimento e adoção de cães e gatos.',
      email: 'contato@patasfelizes.org',
      password_hash: 'senha123',
      whatsapp: '11999990002',
      address: 'Avenida Central, 456',
      city: normalizeCityName('Rio de Janeiro'),
      state: 'RJ',
      cep: '20040002',
    },
    {
      id: randomUUID(),
      name: 'Mundo Animal',
      description: 'Cuidando dos animais que precisam de um lar.',
      email: 'contato@mundoanimal.org',
      password_hash: 'senha123',
      whatsapp: '11999990003',
      address: 'Rua dos Bichos, 789',
      city: normalizeCityName('Curitiba'),
      state: 'PR',
      cep: '80010030',
    },
    {
      id: randomUUID(),
      name: 'SOS Pet',
      description: 'Resgate de animais em situação de risco.',
      email: 'contato@sospet.org',
      password_hash: 'senha123',
      whatsapp: '11999990004',
      address: 'Rua Solidária, 321',
      city: normalizeCityName('Belo Horizonte'),
      state: 'MG',
      cep: '30120010',
    },
    {
      id: randomUUID(),
      name: 'Anjos de Patas',
      description: 'ONG dedicada ao bem-estar dos animais.',
      email: 'contato@anjosdepatas.org',
      password_hash: 'senha123',
      whatsapp: '11999990005',
      address: 'Avenida Amor Animal, 654',
      city: normalizeCityName('Porto Alegre'),
      state: 'RS',
      cep: '90040020',
    },
  ]

  await prisma.org.createMany({ data: orgs })

  console.log('✅ Orgs created')
  type PetType = Prisma.PetUncheckedCreateInput & { photos: string[] }
  const pets: PetType[] = [
    {
      id: randomUUID(),
      org_id: orgs[0].id,
      name: 'Apollo',
      description: 'Cão dócil e adora crianças.',
      age: Age.adult,
      size: 'medium',
      energy_level: 'high',
      independence_level: 'medium',
      environment: 'medium',
      breed: 'Bernedoodle',
      sex: 'male',
      type: 'dog',
      city: normalizeCityName('São Paulo'),
      state: 'SP',
      photos: ['/pets/bernedoodle.jpg'],
    },
    {
      id: randomUUID(),
      org_id: orgs[0].id,
      name: 'Maya',
      description: 'Cão inteligente e ágil, ótimo para famílias.',
      age: Age.puppy,
      size: 'medium',
      energy_level: 'high',
      independence_level: 'medium',
      environment: 'medium',
      breed: 'Border Collie',
      sex: 'female',
      type: 'dog',
      city: normalizeCityName('São Paulo'),
      state: 'SP',
      photos: ['/pets/border-collie.png'],
    },
    {
      id: randomUUID(),
      org_id: orgs[1].id,
      name: 'Zeca',
      description: 'Muito carinhoso e companheiro.',
      age: Age.adult,
      size: 'large',
      energy_level: 'high',
      independence_level: 'medium',
      environment: 'large',
      breed: 'Vira-lata caramelo',
      sex: 'male',
      type: 'dog',
      city: normalizeCityName('Rio de Janeiro'),
      state: 'RJ',
      photos: ['/pets/caramelo.png'],
    },
    {
      id: randomUUID(),
      org_id: orgs[1].id,
      name: 'Lili',
      description: 'Pequena, carinhosa e adora brincar.',
      age: Age.adult,
      size: 'small',
      energy_level: 'high',
      independence_level: 'low',
      environment: 'small',
      breed: 'Chihuahua',
      sex: 'female',
      type: 'dog',
      city: normalizeCityName('Rio de Janeiro'),
      state: 'RJ',
      photos: ['/pets/chihuahua.jpg'],
    },
    {
      id: randomUUID(),
      org_id: orgs[2].id,
      name: 'Ragnar',
      description: 'Muito atento, excelente cão de guarda.',
      age: Age.senior,
      size: 'large',
      energy_level: 'medium',
      independence_level: 'high',
      environment: 'large',
      breed: 'Doberman',
      sex: 'male',
      type: 'dog',
      city: normalizeCityName('Curitiba'),
      state: 'PR',
      photos: ['/pets/doberman.jpg'],
    },
    {
      id: randomUUID(),
      org_id: orgs[2].id,
      name: 'Lola',
      description: 'Muito doce, brincalhona e sociável.',
      age: Age.puppy,
      size: 'large',
      energy_level: 'high',
      independence_level: 'medium',
      environment: 'large',
      breed: 'Golden Retriever',
      sex: 'female',
      type: 'dog',
      city: normalizeCityName('Curitiba'),
      state: 'PR',
      photos: ['/pets/golden-retriever.jpg'],
    },
    {
      id: randomUUID(),
      org_id: orgs[3].id,
      name: 'Amora',
      description: 'Calma, dócil e muito companheira.',
      age: Age.senior,
      size: 'small',
      energy_level: 'low',
      independence_level: 'medium',
      environment: 'small',
      breed: 'Kokoni',
      sex: 'female',
      type: 'dog',
      city: normalizeCityName('Belo Horizonte'),
      state: 'MG',
      photos: ['/pets/kokoni.jpg'],
    },
    {
      id: randomUUID(),
      org_id: orgs[3].id,
      name: 'Zeus',
      description: 'Grande, protetor e extremamente leal.',
      age: Age.adult,
      size: 'large',
      energy_level: 'high',
      independence_level: 'high',
      environment: 'large',
      breed: 'Kuvasz',
      sex: 'male',
      type: 'dog',
      city: normalizeCityName('Belo Horizonte'),
      state: 'MG',
      photos: ['/pets/kuvaszs.jpg'],
    },
    {
      id: randomUUID(),
      org_id: orgs[4].id,
      name: 'Bruno',
      description: 'Extremamente carinhoso e brincalhão.',
      age: Age.puppy,
      size: 'large',
      energy_level: 'high',
      independence_level: 'medium',
      environment: 'large',
      breed: 'Labrador Retriever',
      sex: 'male',
      type: 'dog',
      city: normalizeCityName('Porto Alegre'),
      state: 'RS',
      photos: ['/pets/labrador-retriever.jpg'],
    },
    {
      id: randomUUID(),
      org_id: orgs[4].id,
      name: 'Stella',
      description: 'Meiga, sociável e se dá bem com crianças.',
      age: Age.adult,
      size: 'medium',
      energy_level: 'medium',
      independence_level: 'low',
      environment: 'medium',
      breed: 'Lapphund Finlandês',
      sex: 'female',
      type: 'dog',
      city: normalizeCityName('Porto Alegre'),
      state: 'RS',
      photos: ['/pets/lapphund-finlandes.jpg'],
    },
    {
      id: randomUUID(),
      org_id: orgs[4].id,
      name: 'Mia',
      description: 'Gata carinhosa, ama colo e é muito sociável.',
      age: Age.adult,
      size: 'medium',
      energy_level: 'medium',
      independence_level: 'low',
      environment: 'medium',
      breed: 'Maine Coon',
      sex: 'female',
      type: 'cat',
      city: normalizeCityName('Porto Alegre'),
      state: 'RS',
      photos: ['/cats/maine-coon.jpg'],
    },
    {
      id: randomUUID(),
      org_id: orgs[4].id,
      name: 'Luna',
      description: 'Gata curiosa, inteligente e muito brincalhona.',
      age: Age.adult,
      size: 'small',
      energy_level: 'high',
      independence_level: 'medium',
      environment: 'small',
      breed: 'Tabby',
      sex: 'female',
      type: 'cat',
      city: normalizeCityName('Porto Alegre'),
      state: 'RS',
      photos: ['/cats/tabby.jpg'],
    },
    {
      id: randomUUID(),
      org_id: orgs[4].id,
      name: 'Simba',
      description: 'Gato dócil e companheiro, adora brincar com bolinhas.',
      age: Age.adult,
      size: 'small',
      energy_level: 'medium',
      independence_level: 'medium',
      environment: 'small',
      breed: 'Tabby',
      sex: 'male',
      type: 'cat',
      city: normalizeCityName('Porto Alegre'),
      state: 'RS',
      photos: ['/cats/tabby2.jpg'],
    },
    {
      id: randomUUID(),
      org_id: orgs[4].id,
      name: 'Nina',
      description: 'Gata tranquila, carinhosa e se adapta bem a apartamentos.',
      age: Age.adult,
      size: 'small',
      energy_level: 'low',
      independence_level: 'medium',
      environment: 'small',
      breed: 'Van Turco',
      sex: 'female',
      type: 'cat',
      city: normalizeCityName('Porto Alegre'),
      state: 'RS',
      photos: ['/cats/van-turco.jpg'],
    },
  ]

  await prisma.pet.createMany({
    data: pets.map(({ photos, ...rest }) => rest),
  })

  const photos = pets.flatMap((pet) =>
    pet.photos.map((url) => ({
      id: randomUUID(),
      pet_id: pet.id as UUID,
      url,
    }))
  )

  await prisma.petPhoto.createMany({
    data: photos,
  })


  console.log('✅ Pets created')

  console.log('🌱 Seed finished successfully!')
}

main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })
