services:
  api-solid-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=findafriend
      - POSTGRESQL_PASSWORD=findafriend
      - POSTGRESQL_DATABASE=findafriend
